### ISSUE TITLE
Не могли бы Вы добавить лицензию к проекту?

### ISSUE THREAD

**Issue by xlam** [CyberBiology/CyberBiology#4]
Здравствуйте, @CyberBi @CyberBiology!

До тех пор, пока Вы не добавите какую-либо из "свободных" лицензий, никто не имеет права изменять или, даже, компилировать Ваш код. Таковы реалии "лицензии по умолчанию", которая действует, если явно не указана какая-либо друга лицензия.

Официальный ресурс от Github для помощи в выборе лицензии для open-source проектов:
[https://choosealicense.com](https://choosealicense.com/)

Наиболее распространенные и рекомендуемые лицензии:
- [GNU GPLv3 ](https://choosealicense.com/licenses/gpl-3.0/)
- [Apache License 2.0 ](https://choosealicense.com/licenses/apache-2.0/)
- [MIT License ](https://choosealicense.com/licenses/mit/)

Если угодно, я мог бы создать Pull Request с любой лицензией, которую пожелаете.

Спасибо.

**Comment by CyberBi** [comment]
Done.
Thank you for assistance.
